name: Process PR to Dev
on:
  pull_request:
    branches:
      - temp
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  branch-naming-rules:
    name: Branch Name Rules Check
    runs-on: ubuntu-latest
    steps:
      - uses: RealLukeMartin/action-branch-name@master
        with:
          regex: '(docs|chore|feat|story|bugfix|hotfix|fix)\/([a-z 0-9])+\/([a-z 0-9 _.-])+' # Regex the branch should match.
          allowed_prefixes: 'docs,chore,feat,story,bugfix,hotfix,fix' # All branches should start with the given prefix
          ignore: main,dev # Ignore exactly matching branch names from convention
          min_length: 10 # Min length of the branch name
          max_length: 120 # Max length of the branch name

  run-linters:
    name: Run Linters
    needs: branch-naming-rules
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  run-tests:
    name: Run Tests
    if: github.event.pull_request.draft == false
    needs: branch-naming-rules
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

  run-build:
    name: Run Build
    if: github.event.pull_request.draft == false
    needs: [run-tests, run-linters]
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build
        run: npm run build:all

  changelog:
    name: Changelog Generator
    needs: [run-tests, run-linters]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reallukemartin/pull-request-changelog-dev@main
        with:
          token: ${{ secrets.GIT_HUB_TOKEN}}
